# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 12:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170811_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tex',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
