# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 12:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_profile_tex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tex',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
